samples: samples.tsv
units: units.tsv

# the sequencing adapter
adapter: ACGGATCGATCGATCGATCGAT

# whether to remove PCR/optical duplicates
rmdup: true

ref:
  # name used in snpeff database
  name: hg19
  genome: /scratch/03988/qscai/GATK/dna-seq-gatk-variant-calling-master/vcf/ucsc.hg19.fasta
  # known variants (e.g. DBSNP)
  known-variants: /scratch/03988/qscai/GATK/dna-seq-gatk-variant-calling-master/vcf/dbsnp_138.hg19.vcf

filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

params:
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  cutadapt:
    pe: ""
    se: ""
